package pos.model;

public class Barcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Barcode.GoodsID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    private String goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Barcode.ColorID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    private String colorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Barcode.SizeID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    private String sizeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Barcode.BarCode
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    private String barcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Barcode.GoodsID
     *
     * @return the value of Barcode.GoodsID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Barcode.GoodsID
     *
     * @param goodsid the value for Barcode.GoodsID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Barcode.ColorID
     *
     * @return the value of Barcode.ColorID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public String getColorid() {
        return colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Barcode.ColorID
     *
     * @param colorid the value for Barcode.ColorID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public void setColorid(String colorid) {
        this.colorid = colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Barcode.SizeID
     *
     * @return the value of Barcode.SizeID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public String getSizeid() {
        return sizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Barcode.SizeID
     *
     * @param sizeid the value for Barcode.SizeID
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public void setSizeid(String sizeid) {
        this.sizeid = sizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Barcode.BarCode
     *
     * @return the value of Barcode.BarCode
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Barcode.BarCode
     *
     * @param barcode the value for Barcode.BarCode
     *
     * @mbggenerated Tue Jun 20 20:54:16 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
}