package pos.model;

import java.math.BigDecimal;

public class Possalesdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.POSSalesDetailID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Integer possalesdetailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.POSSalesID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String possalesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SN
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Integer sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.GoodsBarcode
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String goodsbarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.GoodsID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.ColorID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String colorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SizeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String sizeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.Quantity
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.UnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.DiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal discountrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.Discount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.Amount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SpecialPriceFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Boolean specialpriceflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.HireRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal hirerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SupplierAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal supplieramount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.DeptDiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal deptdiscountrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.DeptAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal deptamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.EmployeeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.POSSalesNo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String possalesno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.BackAudit
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String backaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.Memo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.RecordFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Integer recordflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID2
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID3
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID4
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID5
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID6
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.RetailSales
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal retailsales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.RetailAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal retailamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.DelFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.FixMoney
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal fixmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.SPID7
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String spid7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.PointRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal pointrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.FactAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal factamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.FixedFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private Integer fixedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.DepartmentID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.Type
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.VIPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String vipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.NonTaxUnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private BigDecimal nontaxunitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSalesDetail.GoodsKind
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    private String goodskind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.POSSalesDetailID
     *
     * @return the value of POSSalesDetail.POSSalesDetailID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Integer getPossalesdetailid() {
        return possalesdetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.POSSalesDetailID
     *
     * @param possalesdetailid the value for POSSalesDetail.POSSalesDetailID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setPossalesdetailid(Integer possalesdetailid) {
        this.possalesdetailid = possalesdetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.POSSalesID
     *
     * @return the value of POSSalesDetail.POSSalesID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getPossalesid() {
        return possalesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.POSSalesID
     *
     * @param possalesid the value for POSSalesDetail.POSSalesID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setPossalesid(String possalesid) {
        this.possalesid = possalesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SN
     *
     * @return the value of POSSalesDetail.SN
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SN
     *
     * @param sn the value for POSSalesDetail.SN
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.GoodsBarcode
     *
     * @return the value of POSSalesDetail.GoodsBarcode
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getGoodsbarcode() {
        return goodsbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.GoodsBarcode
     *
     * @param goodsbarcode the value for POSSalesDetail.GoodsBarcode
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setGoodsbarcode(String goodsbarcode) {
        this.goodsbarcode = goodsbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.GoodsID
     *
     * @return the value of POSSalesDetail.GoodsID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.GoodsID
     *
     * @param goodsid the value for POSSalesDetail.GoodsID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.ColorID
     *
     * @return the value of POSSalesDetail.ColorID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getColorid() {
        return colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.ColorID
     *
     * @param colorid the value for POSSalesDetail.ColorID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setColorid(String colorid) {
        this.colorid = colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SizeID
     *
     * @return the value of POSSalesDetail.SizeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSizeid() {
        return sizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SizeID
     *
     * @param sizeid the value for POSSalesDetail.SizeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSizeid(String sizeid) {
        this.sizeid = sizeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.Quantity
     *
     * @return the value of POSSalesDetail.Quantity
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.Quantity
     *
     * @param quantity the value for POSSalesDetail.Quantity
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.UnitPrice
     *
     * @return the value of POSSalesDetail.UnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.UnitPrice
     *
     * @param unitprice the value for POSSalesDetail.UnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.DiscountRate
     *
     * @return the value of POSSalesDetail.DiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getDiscountrate() {
        return discountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.DiscountRate
     *
     * @param discountrate the value for POSSalesDetail.DiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDiscountrate(BigDecimal discountrate) {
        this.discountrate = discountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.Discount
     *
     * @return the value of POSSalesDetail.Discount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.Discount
     *
     * @param discount the value for POSSalesDetail.Discount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.Amount
     *
     * @return the value of POSSalesDetail.Amount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.Amount
     *
     * @param amount the value for POSSalesDetail.Amount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SpecialPriceFlag
     *
     * @return the value of POSSalesDetail.SpecialPriceFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Boolean getSpecialpriceflag() {
        return specialpriceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SpecialPriceFlag
     *
     * @param specialpriceflag the value for POSSalesDetail.SpecialPriceFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpecialpriceflag(Boolean specialpriceflag) {
        this.specialpriceflag = specialpriceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.HireRate
     *
     * @return the value of POSSalesDetail.HireRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getHirerate() {
        return hirerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.HireRate
     *
     * @param hirerate the value for POSSalesDetail.HireRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setHirerate(BigDecimal hirerate) {
        this.hirerate = hirerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SupplierAmount
     *
     * @return the value of POSSalesDetail.SupplierAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getSupplieramount() {
        return supplieramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SupplierAmount
     *
     * @param supplieramount the value for POSSalesDetail.SupplierAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSupplieramount(BigDecimal supplieramount) {
        this.supplieramount = supplieramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.DeptDiscountRate
     *
     * @return the value of POSSalesDetail.DeptDiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getDeptdiscountrate() {
        return deptdiscountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.DeptDiscountRate
     *
     * @param deptdiscountrate the value for POSSalesDetail.DeptDiscountRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDeptdiscountrate(BigDecimal deptdiscountrate) {
        this.deptdiscountrate = deptdiscountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.DeptAmount
     *
     * @return the value of POSSalesDetail.DeptAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getDeptamount() {
        return deptamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.DeptAmount
     *
     * @param deptamount the value for POSSalesDetail.DeptAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDeptamount(BigDecimal deptamount) {
        this.deptamount = deptamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.EmployeeID
     *
     * @return the value of POSSalesDetail.EmployeeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.EmployeeID
     *
     * @param employeeid the value for POSSalesDetail.EmployeeID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.POSSalesNo
     *
     * @return the value of POSSalesDetail.POSSalesNo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getPossalesno() {
        return possalesno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.POSSalesNo
     *
     * @param possalesno the value for POSSalesDetail.POSSalesNo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setPossalesno(String possalesno) {
        this.possalesno = possalesno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.BackAudit
     *
     * @return the value of POSSalesDetail.BackAudit
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getBackaudit() {
        return backaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.BackAudit
     *
     * @param backaudit the value for POSSalesDetail.BackAudit
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setBackaudit(String backaudit) {
        this.backaudit = backaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID
     *
     * @return the value of POSSalesDetail.SPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid() {
        return spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID
     *
     * @param spid the value for POSSalesDetail.SPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid(String spid) {
        this.spid = spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.Memo
     *
     * @return the value of POSSalesDetail.Memo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.Memo
     *
     * @param memo the value for POSSalesDetail.Memo
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.RecordFlag
     *
     * @return the value of POSSalesDetail.RecordFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Integer getRecordflag() {
        return recordflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.RecordFlag
     *
     * @param recordflag the value for POSSalesDetail.RecordFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setRecordflag(Integer recordflag) {
        this.recordflag = recordflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID2
     *
     * @return the value of POSSalesDetail.SPID2
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid2() {
        return spid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID2
     *
     * @param spid2 the value for POSSalesDetail.SPID2
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid2(String spid2) {
        this.spid2 = spid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID3
     *
     * @return the value of POSSalesDetail.SPID3
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid3() {
        return spid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID3
     *
     * @param spid3 the value for POSSalesDetail.SPID3
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid3(String spid3) {
        this.spid3 = spid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID4
     *
     * @return the value of POSSalesDetail.SPID4
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid4() {
        return spid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID4
     *
     * @param spid4 the value for POSSalesDetail.SPID4
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid4(String spid4) {
        this.spid4 = spid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID5
     *
     * @return the value of POSSalesDetail.SPID5
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid5() {
        return spid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID5
     *
     * @param spid5 the value for POSSalesDetail.SPID5
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid5(String spid5) {
        this.spid5 = spid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID6
     *
     * @return the value of POSSalesDetail.SPID6
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid6() {
        return spid6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID6
     *
     * @param spid6 the value for POSSalesDetail.SPID6
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid6(String spid6) {
        this.spid6 = spid6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.RetailSales
     *
     * @return the value of POSSalesDetail.RetailSales
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getRetailsales() {
        return retailsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.RetailSales
     *
     * @param retailsales the value for POSSalesDetail.RetailSales
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setRetailsales(BigDecimal retailsales) {
        this.retailsales = retailsales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.RetailAmount
     *
     * @return the value of POSSalesDetail.RetailAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getRetailamount() {
        return retailamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.RetailAmount
     *
     * @param retailamount the value for POSSalesDetail.RetailAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setRetailamount(BigDecimal retailamount) {
        this.retailamount = retailamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.DelFlag
     *
     * @return the value of POSSalesDetail.DelFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.DelFlag
     *
     * @param delflag the value for POSSalesDetail.DelFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.FixMoney
     *
     * @return the value of POSSalesDetail.FixMoney
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getFixmoney() {
        return fixmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.FixMoney
     *
     * @param fixmoney the value for POSSalesDetail.FixMoney
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setFixmoney(BigDecimal fixmoney) {
        this.fixmoney = fixmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.SPID7
     *
     * @return the value of POSSalesDetail.SPID7
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getSpid7() {
        return spid7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.SPID7
     *
     * @param spid7 the value for POSSalesDetail.SPID7
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setSpid7(String spid7) {
        this.spid7 = spid7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.PointRate
     *
     * @return the value of POSSalesDetail.PointRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getPointrate() {
        return pointrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.PointRate
     *
     * @param pointrate the value for POSSalesDetail.PointRate
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setPointrate(BigDecimal pointrate) {
        this.pointrate = pointrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.FactAmount
     *
     * @return the value of POSSalesDetail.FactAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getFactamount() {
        return factamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.FactAmount
     *
     * @param factamount the value for POSSalesDetail.FactAmount
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setFactamount(BigDecimal factamount) {
        this.factamount = factamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.FixedFlag
     *
     * @return the value of POSSalesDetail.FixedFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public Integer getFixedflag() {
        return fixedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.FixedFlag
     *
     * @param fixedflag the value for POSSalesDetail.FixedFlag
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setFixedflag(Integer fixedflag) {
        this.fixedflag = fixedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.DepartmentID
     *
     * @return the value of POSSalesDetail.DepartmentID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.DepartmentID
     *
     * @param departmentid the value for POSSalesDetail.DepartmentID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.Type
     *
     * @return the value of POSSalesDetail.Type
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.Type
     *
     * @param type the value for POSSalesDetail.Type
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.VIPID
     *
     * @return the value of POSSalesDetail.VIPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.VIPID
     *
     * @param vipid the value for POSSalesDetail.VIPID
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setVipid(String vipid) {
        this.vipid = vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.NonTaxUnitPrice
     *
     * @return the value of POSSalesDetail.NonTaxUnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public BigDecimal getNontaxunitprice() {
        return nontaxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.NonTaxUnitPrice
     *
     * @param nontaxunitprice the value for POSSalesDetail.NonTaxUnitPrice
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setNontaxunitprice(BigDecimal nontaxunitprice) {
        this.nontaxunitprice = nontaxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSalesDetail.GoodsKind
     *
     * @return the value of POSSalesDetail.GoodsKind
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public String getGoodskind() {
        return goodskind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSalesDetail.GoodsKind
     *
     * @param goodskind the value for POSSalesDetail.GoodsKind
     *
     * @mbggenerated Thu May 17 22:32:20 CST 2018
     */
    public void setGoodskind(String goodskind) {
        this.goodskind = goodskind;
    }
}