package pos.model;

import java.math.BigDecimal;
import java.util.Date;

public class Possales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.PosSalesID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String possalesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.No
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Type
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Date
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.SPType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String sptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CustomerCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String customercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DepartmentID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.EmployeeID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.QuantitySum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer quantitysum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DiscountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal discountsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal amountsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AlterMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal altermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DiscountMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal discountmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AddMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal addmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CardMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cardmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashPaper
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashpaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ReturnMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal returnmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.MadeBy
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String madeby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.MadeByDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Date madebydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AuditFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Boolean auditflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Audit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String audit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AuditDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Date auditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Year
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Month
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DaySumFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Boolean daysumflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.SendFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Boolean sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Memo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ReceivalFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer receivalflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ReceivalID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String receivalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.VIPCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String vipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.TallyFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Boolean tallyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.OnDutyNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String ondutyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.OrderFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer orderflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.OrderNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.OrderAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashAmount1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashamount1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashRate1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashrate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashAmount2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashamount2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashRate2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal cashrate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CardType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Employee2ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String employee2id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Employee3ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String employee3id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.WebNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String webno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.SalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal salespoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CounterNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String counterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CashPaperNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String cashpaperno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.PresentAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal presentamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DepositAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal depositamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.VIPID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String vipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.PointRate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal pointrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ThisSalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer thissalespoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ExchangedPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer exchangedpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.DelFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Short delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.CommandFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String commandflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ReturnCash
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal returncash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.VIPDeposit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal vipdeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.Charge
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.FactAmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal factamountsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.EShopOrderID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Long eshoporderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.print_shipping
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer printShipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.print_send
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer printSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.AnnualFeeCount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Integer annualfeecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.TaxCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal taxcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.LogisticsCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private BigDecimal logisticscost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.BusinessDeptID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private String businessdeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.UpdateFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Boolean updateflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POSSales.ReturnID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    private Long returnid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.PosSalesID
     *
     * @return the value of POSSales.PosSalesID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getPossalesid() {
        return possalesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.PosSalesID
     *
     * @param possalesid the value for POSSales.PosSalesID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setPossalesid(String possalesid) {
        this.possalesid = possalesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.No
     *
     * @return the value of POSSales.No
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.No
     *
     * @param no the value for POSSales.No
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Type
     *
     * @return the value of POSSales.Type
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Type
     *
     * @param type the value for POSSales.Type
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Date
     *
     * @return the value of POSSales.Date
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Date
     *
     * @param date the value for POSSales.Date
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.SPType
     *
     * @return the value of POSSales.SPType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getSptype() {
        return sptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.SPType
     *
     * @param sptype the value for POSSales.SPType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setSptype(String sptype) {
        this.sptype = sptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CustomerCode
     *
     * @return the value of POSSales.CustomerCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCustomercode() {
        return customercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CustomerCode
     *
     * @param customercode the value for POSSales.CustomerCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DepartmentID
     *
     * @return the value of POSSales.DepartmentID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DepartmentID
     *
     * @param departmentid the value for POSSales.DepartmentID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.EmployeeID
     *
     * @return the value of POSSales.EmployeeID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.EmployeeID
     *
     * @param employeeid the value for POSSales.EmployeeID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.QuantitySum
     *
     * @return the value of POSSales.QuantitySum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getQuantitysum() {
        return quantitysum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.QuantitySum
     *
     * @param quantitysum the value for POSSales.QuantitySum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setQuantitysum(Integer quantitysum) {
        this.quantitysum = quantitysum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DiscountSum
     *
     * @return the value of POSSales.DiscountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getDiscountsum() {
        return discountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DiscountSum
     *
     * @param discountsum the value for POSSales.DiscountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDiscountsum(BigDecimal discountsum) {
        this.discountsum = discountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AmountSum
     *
     * @return the value of POSSales.AmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getAmountsum() {
        return amountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AmountSum
     *
     * @param amountsum the value for POSSales.AmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAmountsum(BigDecimal amountsum) {
        this.amountsum = amountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AlterMoney
     *
     * @return the value of POSSales.AlterMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getAltermoney() {
        return altermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AlterMoney
     *
     * @param altermoney the value for POSSales.AlterMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAltermoney(BigDecimal altermoney) {
        this.altermoney = altermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DiscountMoney
     *
     * @return the value of POSSales.DiscountMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getDiscountmoney() {
        return discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DiscountMoney
     *
     * @param discountmoney the value for POSSales.DiscountMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDiscountmoney(BigDecimal discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AddMoney
     *
     * @return the value of POSSales.AddMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getAddmoney() {
        return addmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AddMoney
     *
     * @param addmoney the value for POSSales.AddMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAddmoney(BigDecimal addmoney) {
        this.addmoney = addmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CardMoney
     *
     * @return the value of POSSales.CardMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCardmoney() {
        return cardmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CardMoney
     *
     * @param cardmoney the value for POSSales.CardMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCardmoney(BigDecimal cardmoney) {
        this.cardmoney = cardmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashMoney
     *
     * @return the value of POSSales.CashMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashmoney() {
        return cashmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashMoney
     *
     * @param cashmoney the value for POSSales.CashMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashmoney(BigDecimal cashmoney) {
        this.cashmoney = cashmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashPaper
     *
     * @return the value of POSSales.CashPaper
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashpaper() {
        return cashpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashPaper
     *
     * @param cashpaper the value for POSSales.CashPaper
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashpaper(BigDecimal cashpaper) {
        this.cashpaper = cashpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ReturnMoney
     *
     * @return the value of POSSales.ReturnMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getReturnmoney() {
        return returnmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ReturnMoney
     *
     * @param returnmoney the value for POSSales.ReturnMoney
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setReturnmoney(BigDecimal returnmoney) {
        this.returnmoney = returnmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.MadeBy
     *
     * @return the value of POSSales.MadeBy
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getMadeby() {
        return madeby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.MadeBy
     *
     * @param madeby the value for POSSales.MadeBy
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setMadeby(String madeby) {
        this.madeby = madeby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.MadeByDate
     *
     * @return the value of POSSales.MadeByDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Date getMadebydate() {
        return madebydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.MadeByDate
     *
     * @param madebydate the value for POSSales.MadeByDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setMadebydate(Date madebydate) {
        this.madebydate = madebydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AuditFlag
     *
     * @return the value of POSSales.AuditFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Boolean getAuditflag() {
        return auditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AuditFlag
     *
     * @param auditflag the value for POSSales.AuditFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAuditflag(Boolean auditflag) {
        this.auditflag = auditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Audit
     *
     * @return the value of POSSales.Audit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Audit
     *
     * @param audit the value for POSSales.Audit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAudit(String audit) {
        this.audit = audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AuditDate
     *
     * @return the value of POSSales.AuditDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Date getAuditdate() {
        return auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AuditDate
     *
     * @param auditdate the value for POSSales.AuditDate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Year
     *
     * @return the value of POSSales.Year
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Year
     *
     * @param year the value for POSSales.Year
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Month
     *
     * @return the value of POSSales.Month
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Month
     *
     * @param month the value for POSSales.Month
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DaySumFlag
     *
     * @return the value of POSSales.DaySumFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Boolean getDaysumflag() {
        return daysumflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DaySumFlag
     *
     * @param daysumflag the value for POSSales.DaySumFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDaysumflag(Boolean daysumflag) {
        this.daysumflag = daysumflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.SendFlag
     *
     * @return the value of POSSales.SendFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Boolean getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.SendFlag
     *
     * @param sendflag the value for POSSales.SendFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setSendflag(Boolean sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Memo
     *
     * @return the value of POSSales.Memo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Memo
     *
     * @param memo the value for POSSales.Memo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ReceivalFlag
     *
     * @return the value of POSSales.ReceivalFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getReceivalflag() {
        return receivalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ReceivalFlag
     *
     * @param receivalflag the value for POSSales.ReceivalFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setReceivalflag(Integer receivalflag) {
        this.receivalflag = receivalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ReceivalID
     *
     * @return the value of POSSales.ReceivalID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getReceivalid() {
        return receivalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ReceivalID
     *
     * @param receivalid the value for POSSales.ReceivalID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setReceivalid(String receivalid) {
        this.receivalid = receivalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.VIPCode
     *
     * @return the value of POSSales.VIPCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getVipcode() {
        return vipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.VIPCode
     *
     * @param vipcode the value for POSSales.VIPCode
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setVipcode(String vipcode) {
        this.vipcode = vipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.TallyFlag
     *
     * @return the value of POSSales.TallyFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Boolean getTallyflag() {
        return tallyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.TallyFlag
     *
     * @param tallyflag the value for POSSales.TallyFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setTallyflag(Boolean tallyflag) {
        this.tallyflag = tallyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.OnDutyNo
     *
     * @return the value of POSSales.OnDutyNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getOndutyno() {
        return ondutyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.OnDutyNo
     *
     * @param ondutyno the value for POSSales.OnDutyNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setOndutyno(String ondutyno) {
        this.ondutyno = ondutyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.OrderFlag
     *
     * @return the value of POSSales.OrderFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getOrderflag() {
        return orderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.OrderFlag
     *
     * @param orderflag the value for POSSales.OrderFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setOrderflag(Integer orderflag) {
        this.orderflag = orderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.OrderNo
     *
     * @return the value of POSSales.OrderNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.OrderNo
     *
     * @param orderno the value for POSSales.OrderNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.OrderAmount
     *
     * @return the value of POSSales.OrderAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.OrderAmount
     *
     * @param orderamount the value for POSSales.OrderAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashAmount1
     *
     * @return the value of POSSales.CashAmount1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashamount1() {
        return cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashAmount1
     *
     * @param cashamount1 the value for POSSales.CashAmount1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashamount1(BigDecimal cashamount1) {
        this.cashamount1 = cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashRate1
     *
     * @return the value of POSSales.CashRate1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashrate1() {
        return cashrate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashRate1
     *
     * @param cashrate1 the value for POSSales.CashRate1
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashrate1(BigDecimal cashrate1) {
        this.cashrate1 = cashrate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashAmount2
     *
     * @return the value of POSSales.CashAmount2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashamount2() {
        return cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashAmount2
     *
     * @param cashamount2 the value for POSSales.CashAmount2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashamount2(BigDecimal cashamount2) {
        this.cashamount2 = cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashRate2
     *
     * @return the value of POSSales.CashRate2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getCashrate2() {
        return cashrate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashRate2
     *
     * @param cashrate2 the value for POSSales.CashRate2
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashrate2(BigDecimal cashrate2) {
        this.cashrate2 = cashrate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CardType
     *
     * @return the value of POSSales.CardType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CardType
     *
     * @param cardtype the value for POSSales.CardType
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Employee2ID
     *
     * @return the value of POSSales.Employee2ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getEmployee2id() {
        return employee2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Employee2ID
     *
     * @param employee2id the value for POSSales.Employee2ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setEmployee2id(String employee2id) {
        this.employee2id = employee2id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Employee3ID
     *
     * @return the value of POSSales.Employee3ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getEmployee3id() {
        return employee3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Employee3ID
     *
     * @param employee3id the value for POSSales.Employee3ID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setEmployee3id(String employee3id) {
        this.employee3id = employee3id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.WebNo
     *
     * @return the value of POSSales.WebNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getWebno() {
        return webno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.WebNo
     *
     * @param webno the value for POSSales.WebNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setWebno(String webno) {
        this.webno = webno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.SalesPoint
     *
     * @return the value of POSSales.SalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getSalespoint() {
        return salespoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.SalesPoint
     *
     * @param salespoint the value for POSSales.SalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setSalespoint(BigDecimal salespoint) {
        this.salespoint = salespoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CounterNo
     *
     * @return the value of POSSales.CounterNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCounterno() {
        return counterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CounterNo
     *
     * @param counterno the value for POSSales.CounterNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCounterno(String counterno) {
        this.counterno = counterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CashPaperNo
     *
     * @return the value of POSSales.CashPaperNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCashpaperno() {
        return cashpaperno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CashPaperNo
     *
     * @param cashpaperno the value for POSSales.CashPaperNo
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCashpaperno(String cashpaperno) {
        this.cashpaperno = cashpaperno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.PresentAmount
     *
     * @return the value of POSSales.PresentAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getPresentamount() {
        return presentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.PresentAmount
     *
     * @param presentamount the value for POSSales.PresentAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setPresentamount(BigDecimal presentamount) {
        this.presentamount = presentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DepositAmount
     *
     * @return the value of POSSales.DepositAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getDepositamount() {
        return depositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DepositAmount
     *
     * @param depositamount the value for POSSales.DepositAmount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDepositamount(BigDecimal depositamount) {
        this.depositamount = depositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.VIPID
     *
     * @return the value of POSSales.VIPID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.VIPID
     *
     * @param vipid the value for POSSales.VIPID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setVipid(String vipid) {
        this.vipid = vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.PointRate
     *
     * @return the value of POSSales.PointRate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getPointrate() {
        return pointrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.PointRate
     *
     * @param pointrate the value for POSSales.PointRate
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setPointrate(BigDecimal pointrate) {
        this.pointrate = pointrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ThisSalesPoint
     *
     * @return the value of POSSales.ThisSalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getThissalespoint() {
        return thissalespoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ThisSalesPoint
     *
     * @param thissalespoint the value for POSSales.ThisSalesPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setThissalespoint(Integer thissalespoint) {
        this.thissalespoint = thissalespoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ExchangedPoint
     *
     * @return the value of POSSales.ExchangedPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getExchangedpoint() {
        return exchangedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ExchangedPoint
     *
     * @param exchangedpoint the value for POSSales.ExchangedPoint
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setExchangedpoint(Integer exchangedpoint) {
        this.exchangedpoint = exchangedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.DelFlag
     *
     * @return the value of POSSales.DelFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Short getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.DelFlag
     *
     * @param delflag the value for POSSales.DelFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setDelflag(Short delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.CommandFlag
     *
     * @return the value of POSSales.CommandFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCommandflag() {
        return commandflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.CommandFlag
     *
     * @param commandflag the value for POSSales.CommandFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCommandflag(String commandflag) {
        this.commandflag = commandflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ReturnCash
     *
     * @return the value of POSSales.ReturnCash
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getReturncash() {
        return returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ReturnCash
     *
     * @param returncash the value for POSSales.ReturnCash
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setReturncash(BigDecimal returncash) {
        this.returncash = returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.VIPDeposit
     *
     * @return the value of POSSales.VIPDeposit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getVipdeposit() {
        return vipdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.VIPDeposit
     *
     * @param vipdeposit the value for POSSales.VIPDeposit
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setVipdeposit(BigDecimal vipdeposit) {
        this.vipdeposit = vipdeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.Charge
     *
     * @return the value of POSSales.Charge
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.Charge
     *
     * @param charge the value for POSSales.Charge
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.FactAmountSum
     *
     * @return the value of POSSales.FactAmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getFactamountsum() {
        return factamountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.FactAmountSum
     *
     * @param factamountsum the value for POSSales.FactAmountSum
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setFactamountsum(BigDecimal factamountsum) {
        this.factamountsum = factamountsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.EShopOrderID
     *
     * @return the value of POSSales.EShopOrderID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Long getEshoporderid() {
        return eshoporderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.EShopOrderID
     *
     * @param eshoporderid the value for POSSales.EShopOrderID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setEshoporderid(Long eshoporderid) {
        this.eshoporderid = eshoporderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.print_shipping
     *
     * @return the value of POSSales.print_shipping
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getPrintShipping() {
        return printShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.print_shipping
     *
     * @param printShipping the value for POSSales.print_shipping
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setPrintShipping(Integer printShipping) {
        this.printShipping = printShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.print_send
     *
     * @return the value of POSSales.print_send
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getPrintSend() {
        return printSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.print_send
     *
     * @param printSend the value for POSSales.print_send
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setPrintSend(Integer printSend) {
        this.printSend = printSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.AnnualFeeCount
     *
     * @return the value of POSSales.AnnualFeeCount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Integer getAnnualfeecount() {
        return annualfeecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.AnnualFeeCount
     *
     * @param annualfeecount the value for POSSales.AnnualFeeCount
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setAnnualfeecount(Integer annualfeecount) {
        this.annualfeecount = annualfeecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.TaxCost
     *
     * @return the value of POSSales.TaxCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getTaxcost() {
        return taxcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.TaxCost
     *
     * @param taxcost the value for POSSales.TaxCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setTaxcost(BigDecimal taxcost) {
        this.taxcost = taxcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.LogisticsCost
     *
     * @return the value of POSSales.LogisticsCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public BigDecimal getLogisticscost() {
        return logisticscost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.LogisticsCost
     *
     * @param logisticscost the value for POSSales.LogisticsCost
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setLogisticscost(BigDecimal logisticscost) {
        this.logisticscost = logisticscost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.BusinessDeptID
     *
     * @return the value of POSSales.BusinessDeptID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public String getBusinessdeptid() {
        return businessdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.BusinessDeptID
     *
     * @param businessdeptid the value for POSSales.BusinessDeptID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setBusinessdeptid(String businessdeptid) {
        this.businessdeptid = businessdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.UpdateFlag
     *
     * @return the value of POSSales.UpdateFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Boolean getUpdateflag() {
        return updateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.UpdateFlag
     *
     * @param updateflag the value for POSSales.UpdateFlag
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setUpdateflag(Boolean updateflag) {
        this.updateflag = updateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSSales.ReturnID
     *
     * @return the value of POSSales.ReturnID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public Long getReturnid() {
        return returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSSales.ReturnID
     *
     * @param returnid the value for POSSales.ReturnID
     *
     * @mbggenerated Thu May 17 22:31:43 CST 2018
     */
    public void setReturnid(Long returnid) {
        this.returnid = returnid;
    }
}