package pos.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.No
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Password
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.DiscountRatePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean discountratepermitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.DiscountRate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private BigDecimal discountrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SuperSalesFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean supersalesflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean unauditflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.OnlyDispUnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean onlydispunauditflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.DepartmentID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SuperFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean superflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.GroupID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.OnlyModifySelfFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean onlymodifyselfflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.DateLimit
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Integer datelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.InUseFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean inuseflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SalesTemplateFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean salestemplateflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SalesDescription
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String salesdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UnitPricePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean unitpricepermitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.LoginStartTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String loginstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.LoginEndTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String loginendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.NoSaturdayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean nosaturdayflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.NoSundayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean nosundayflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.NoHolidayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean noholidayflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.ModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.MobilPhone
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String mobilphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.MaxDiscount
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private BigDecimal maxdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.MaxFullDis
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private BigDecimal maxfulldis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.MobilePhone2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String mobilephone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.POSAdminFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean posadminflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.OnlySelfInvoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean onlyselfinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.HelpCode
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String helpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SendMailAdd
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String sendmailadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SMTPServer
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String smtpserver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SMTPUserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String smtpusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SMTPPassword
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String smtppassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UseBrandRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean usebrandright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UsePicRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean usepicright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CanModifyNo
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean canmodifyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CustomerID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.HisOwnDepartmentVoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean hisowndepartmentvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CanModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean canmodifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.ModifyPriceOnly
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean modifypriceonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CanEditPassed
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean caneditpassed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SuperSalesXYFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean supersalesxyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.SuperSalesBackFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean supersalesbackflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.NoMoreLoginFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean nomoreloginflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.StopFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean stopflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.AllDeptRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean alldeptright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.DiscountRatePermitFlag2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Boolean discountratepermitflag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.RoleID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserID
     *
     * @return the value of User.UserID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserID
     *
     * @param userid the value for User.UserID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.No
     *
     * @return the value of User.No
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.No
     *
     * @param no the value for User.No
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserName
     *
     * @return the value of User.UserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserName
     *
     * @param username the value for User.UserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Password
     *
     * @return the value of User.Password
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Password
     *
     * @param password the value for User.Password
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.DiscountRatePermitFlag
     *
     * @return the value of User.DiscountRatePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getDiscountratepermitflag() {
        return discountratepermitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.DiscountRatePermitFlag
     *
     * @param discountratepermitflag the value for User.DiscountRatePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setDiscountratepermitflag(Boolean discountratepermitflag) {
        this.discountratepermitflag = discountratepermitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.DiscountRate
     *
     * @return the value of User.DiscountRate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public BigDecimal getDiscountrate() {
        return discountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.DiscountRate
     *
     * @param discountrate the value for User.DiscountRate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setDiscountrate(BigDecimal discountrate) {
        this.discountrate = discountrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SuperSalesFlag
     *
     * @return the value of User.SuperSalesFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getSupersalesflag() {
        return supersalesflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SuperSalesFlag
     *
     * @param supersalesflag the value for User.SuperSalesFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSupersalesflag(Boolean supersalesflag) {
        this.supersalesflag = supersalesflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UnAuditFlag
     *
     * @return the value of User.UnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getUnauditflag() {
        return unauditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UnAuditFlag
     *
     * @param unauditflag the value for User.UnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUnauditflag(Boolean unauditflag) {
        this.unauditflag = unauditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.OnlyDispUnAuditFlag
     *
     * @return the value of User.OnlyDispUnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getOnlydispunauditflag() {
        return onlydispunauditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.OnlyDispUnAuditFlag
     *
     * @param onlydispunauditflag the value for User.OnlyDispUnAuditFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setOnlydispunauditflag(Boolean onlydispunauditflag) {
        this.onlydispunauditflag = onlydispunauditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.DepartmentID
     *
     * @return the value of User.DepartmentID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.DepartmentID
     *
     * @param departmentid the value for User.DepartmentID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SuperFlag
     *
     * @return the value of User.SuperFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getSuperflag() {
        return superflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SuperFlag
     *
     * @param superflag the value for User.SuperFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSuperflag(Boolean superflag) {
        this.superflag = superflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.GroupID
     *
     * @return the value of User.GroupID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.GroupID
     *
     * @param groupid the value for User.GroupID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.OnlyModifySelfFlag
     *
     * @return the value of User.OnlyModifySelfFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getOnlymodifyselfflag() {
        return onlymodifyselfflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.OnlyModifySelfFlag
     *
     * @param onlymodifyselfflag the value for User.OnlyModifySelfFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setOnlymodifyselfflag(Boolean onlymodifyselfflag) {
        this.onlymodifyselfflag = onlymodifyselfflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.DateLimit
     *
     * @return the value of User.DateLimit
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Integer getDatelimit() {
        return datelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.DateLimit
     *
     * @param datelimit the value for User.DateLimit
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setDatelimit(Integer datelimit) {
        this.datelimit = datelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.InUseFlag
     *
     * @return the value of User.InUseFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getInuseflag() {
        return inuseflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.InUseFlag
     *
     * @param inuseflag the value for User.InUseFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setInuseflag(Boolean inuseflag) {
        this.inuseflag = inuseflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SalesTemplateFlag
     *
     * @return the value of User.SalesTemplateFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getSalestemplateflag() {
        return salestemplateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SalesTemplateFlag
     *
     * @param salestemplateflag the value for User.SalesTemplateFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSalestemplateflag(Boolean salestemplateflag) {
        this.salestemplateflag = salestemplateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SalesDescription
     *
     * @return the value of User.SalesDescription
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getSalesdescription() {
        return salesdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SalesDescription
     *
     * @param salesdescription the value for User.SalesDescription
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSalesdescription(String salesdescription) {
        this.salesdescription = salesdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UnitPricePermitFlag
     *
     * @return the value of User.UnitPricePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getUnitpricepermitflag() {
        return unitpricepermitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UnitPricePermitFlag
     *
     * @param unitpricepermitflag the value for User.UnitPricePermitFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUnitpricepermitflag(Boolean unitpricepermitflag) {
        this.unitpricepermitflag = unitpricepermitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.LoginStartTime
     *
     * @return the value of User.LoginStartTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getLoginstarttime() {
        return loginstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.LoginStartTime
     *
     * @param loginstarttime the value for User.LoginStartTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setLoginstarttime(String loginstarttime) {
        this.loginstarttime = loginstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.LoginEndTime
     *
     * @return the value of User.LoginEndTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getLoginendtime() {
        return loginendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.LoginEndTime
     *
     * @param loginendtime the value for User.LoginEndTime
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setLoginendtime(String loginendtime) {
        this.loginendtime = loginendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.NoSaturdayFlag
     *
     * @return the value of User.NoSaturdayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getNosaturdayflag() {
        return nosaturdayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.NoSaturdayFlag
     *
     * @param nosaturdayflag the value for User.NoSaturdayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setNosaturdayflag(Boolean nosaturdayflag) {
        this.nosaturdayflag = nosaturdayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.NoSundayFlag
     *
     * @return the value of User.NoSundayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getNosundayflag() {
        return nosundayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.NoSundayFlag
     *
     * @param nosundayflag the value for User.NoSundayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setNosundayflag(Boolean nosundayflag) {
        this.nosundayflag = nosundayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.NoHolidayFlag
     *
     * @return the value of User.NoHolidayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getNoholidayflag() {
        return noholidayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.NoHolidayFlag
     *
     * @param noholidayflag the value for User.NoHolidayFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setNoholidayflag(Boolean noholidayflag) {
        this.noholidayflag = noholidayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.ModifyDate
     *
     * @return the value of User.ModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.ModifyDate
     *
     * @param modifydate the value for User.ModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.MobilPhone
     *
     * @return the value of User.MobilPhone
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getMobilphone() {
        return mobilphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.MobilPhone
     *
     * @param mobilphone the value for User.MobilPhone
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setMobilphone(String mobilphone) {
        this.mobilphone = mobilphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.MaxDiscount
     *
     * @return the value of User.MaxDiscount
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public BigDecimal getMaxdiscount() {
        return maxdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.MaxDiscount
     *
     * @param maxdiscount the value for User.MaxDiscount
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setMaxdiscount(BigDecimal maxdiscount) {
        this.maxdiscount = maxdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.MaxFullDis
     *
     * @return the value of User.MaxFullDis
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public BigDecimal getMaxfulldis() {
        return maxfulldis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.MaxFullDis
     *
     * @param maxfulldis the value for User.MaxFullDis
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setMaxfulldis(BigDecimal maxfulldis) {
        this.maxfulldis = maxfulldis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.MobilePhone2
     *
     * @return the value of User.MobilePhone2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getMobilephone2() {
        return mobilephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.MobilePhone2
     *
     * @param mobilephone2 the value for User.MobilePhone2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setMobilephone2(String mobilephone2) {
        this.mobilephone2 = mobilephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.POSAdminFlag
     *
     * @return the value of User.POSAdminFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getPosadminflag() {
        return posadminflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.POSAdminFlag
     *
     * @param posadminflag the value for User.POSAdminFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setPosadminflag(Boolean posadminflag) {
        this.posadminflag = posadminflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.OnlySelfInvoice
     *
     * @return the value of User.OnlySelfInvoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getOnlyselfinvoice() {
        return onlyselfinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.OnlySelfInvoice
     *
     * @param onlyselfinvoice the value for User.OnlySelfInvoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setOnlyselfinvoice(Boolean onlyselfinvoice) {
        this.onlyselfinvoice = onlyselfinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.HelpCode
     *
     * @return the value of User.HelpCode
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getHelpcode() {
        return helpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.HelpCode
     *
     * @param helpcode the value for User.HelpCode
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setHelpcode(String helpcode) {
        this.helpcode = helpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SendMailAdd
     *
     * @return the value of User.SendMailAdd
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getSendmailadd() {
        return sendmailadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SendMailAdd
     *
     * @param sendmailadd the value for User.SendMailAdd
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSendmailadd(String sendmailadd) {
        this.sendmailadd = sendmailadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SMTPServer
     *
     * @return the value of User.SMTPServer
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getSmtpserver() {
        return smtpserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SMTPServer
     *
     * @param smtpserver the value for User.SMTPServer
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSmtpserver(String smtpserver) {
        this.smtpserver = smtpserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SMTPUserName
     *
     * @return the value of User.SMTPUserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getSmtpusername() {
        return smtpusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SMTPUserName
     *
     * @param smtpusername the value for User.SMTPUserName
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSmtpusername(String smtpusername) {
        this.smtpusername = smtpusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SMTPPassword
     *
     * @return the value of User.SMTPPassword
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getSmtppassword() {
        return smtppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SMTPPassword
     *
     * @param smtppassword the value for User.SMTPPassword
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSmtppassword(String smtppassword) {
        this.smtppassword = smtppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UseBrandRight
     *
     * @return the value of User.UseBrandRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getUsebrandright() {
        return usebrandright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UseBrandRight
     *
     * @param usebrandright the value for User.UseBrandRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUsebrandright(Boolean usebrandright) {
        this.usebrandright = usebrandright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UsePicRight
     *
     * @return the value of User.UsePicRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getUsepicright() {
        return usepicright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UsePicRight
     *
     * @param usepicright the value for User.UsePicRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setUsepicright(Boolean usepicright) {
        this.usepicright = usepicright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CanModifyNo
     *
     * @return the value of User.CanModifyNo
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getCanmodifyno() {
        return canmodifyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CanModifyNo
     *
     * @param canmodifyno the value for User.CanModifyNo
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setCanmodifyno(Boolean canmodifyno) {
        this.canmodifyno = canmodifyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CustomerID
     *
     * @return the value of User.CustomerID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CustomerID
     *
     * @param customerid the value for User.CustomerID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.HisOwnDepartmentVoice
     *
     * @return the value of User.HisOwnDepartmentVoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getHisowndepartmentvoice() {
        return hisowndepartmentvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.HisOwnDepartmentVoice
     *
     * @param hisowndepartmentvoice the value for User.HisOwnDepartmentVoice
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setHisowndepartmentvoice(Boolean hisowndepartmentvoice) {
        this.hisowndepartmentvoice = hisowndepartmentvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CanModifyDate
     *
     * @return the value of User.CanModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getCanmodifydate() {
        return canmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CanModifyDate
     *
     * @param canmodifydate the value for User.CanModifyDate
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setCanmodifydate(Boolean canmodifydate) {
        this.canmodifydate = canmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.ModifyPriceOnly
     *
     * @return the value of User.ModifyPriceOnly
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getModifypriceonly() {
        return modifypriceonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.ModifyPriceOnly
     *
     * @param modifypriceonly the value for User.ModifyPriceOnly
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setModifypriceonly(Boolean modifypriceonly) {
        this.modifypriceonly = modifypriceonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CanEditPassed
     *
     * @return the value of User.CanEditPassed
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getCaneditpassed() {
        return caneditpassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CanEditPassed
     *
     * @param caneditpassed the value for User.CanEditPassed
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setCaneditpassed(Boolean caneditpassed) {
        this.caneditpassed = caneditpassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SuperSalesXYFlag
     *
     * @return the value of User.SuperSalesXYFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getSupersalesxyflag() {
        return supersalesxyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SuperSalesXYFlag
     *
     * @param supersalesxyflag the value for User.SuperSalesXYFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSupersalesxyflag(Boolean supersalesxyflag) {
        this.supersalesxyflag = supersalesxyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.SuperSalesBackFlag
     *
     * @return the value of User.SuperSalesBackFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getSupersalesbackflag() {
        return supersalesbackflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.SuperSalesBackFlag
     *
     * @param supersalesbackflag the value for User.SuperSalesBackFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setSupersalesbackflag(Boolean supersalesbackflag) {
        this.supersalesbackflag = supersalesbackflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.NoMoreLoginFlag
     *
     * @return the value of User.NoMoreLoginFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getNomoreloginflag() {
        return nomoreloginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.NoMoreLoginFlag
     *
     * @param nomoreloginflag the value for User.NoMoreLoginFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setNomoreloginflag(Boolean nomoreloginflag) {
        this.nomoreloginflag = nomoreloginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.StopFlag
     *
     * @return the value of User.StopFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getStopflag() {
        return stopflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.StopFlag
     *
     * @param stopflag the value for User.StopFlag
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setStopflag(Boolean stopflag) {
        this.stopflag = stopflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.AllDeptRight
     *
     * @return the value of User.AllDeptRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getAlldeptright() {
        return alldeptright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.AllDeptRight
     *
     * @param alldeptright the value for User.AllDeptRight
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setAlldeptright(Boolean alldeptright) {
        this.alldeptright = alldeptright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.DiscountRatePermitFlag2
     *
     * @return the value of User.DiscountRatePermitFlag2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Boolean getDiscountratepermitflag2() {
        return discountratepermitflag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.DiscountRatePermitFlag2
     *
     * @param discountratepermitflag2 the value for User.DiscountRatePermitFlag2
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setDiscountratepermitflag2(Boolean discountratepermitflag2) {
        this.discountratepermitflag2 = discountratepermitflag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.RoleID
     *
     * @return the value of User.RoleID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.RoleID
     *
     * @param roleid the value for User.RoleID
     *
     * @mbggenerated Sun Mar 26 15:30:38 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}